-- DropForeignKey
ALTER TABLE "SHOWING" DROP CONSTRAINT "SHOWING_movie_id_fkey";

-- AddForeignKey
ALTER TABLE "SHOWING" ADD CONSTRAINT "SHOWING_movie_id_fkey" FOREIGN KEY ("movie_id") REFERENCES "MOVIE"("movie_id") ON DELETE CASCADE ON UPDATE CASCADE;
